development:
  adapter: sqlite3
  database: db/yomiyomiReader.db
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: db/yomiyomiReader.db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/yomiyomiReader.db
  pool: 5
  timeout: 5000